#base "ClientScheme_astrofonts.res"
#base "ClientScheme_borders.res"
#base "ClientScheme_fonts.res"
#base "ClientScheme_colors.res"

"Scheme" 
{
	"BaseSettings" 
	{
		"ReplayBrowser.BgColor" "DarkBrown"
		"ReplayBrowser.Details.TitleEdit.Carat.FgColor" "LightRed"
		"ReplayBrowser.Button.ArmedBgColor" "TFOrange"
		"ReplayBrowser.Button.DepressedBgColor" "TFOrange"
		"ReplayBrowser.CollectionTitle.FgColor" "LightRed"
		"ReplayBrowser.Warning.FgColor" "White"
		"ReplayBrowser.ScrollBar.SliderButton.FgColor" "TransparentYellow"
		"ReplayBrowser.Search.BgColor" "TanDark"
		"ReplayBrowser.Search.FgColor" "White"
		"Replay.RenderDialog.BgColor" "LighterDarkBrown"
		"Econ.Dialog.BgColor" "Blank"
		"Econ.Button.BgColor" "ButtonBG"
		"Econ.Button.FgColor" "ButtonFont"
		"Econ.Button.ArmedBgColor" "ButtonBGArmed"
		"Econ.Button.ArmedFgColor" "ButtonFontArmed"
		"Econ.Button.DepressedBgColor" "ButtonBGSelect"
		"Econ.Button.DepressedFgColor" "ButtonFontSelect"
		"Econ.Button.PresetDefaultColorFg" "ButtonFont"
		"Econ.Button.PresetArmedColorFg" "ButtonFontArmed"
		"Econ.Button.PresetDepressedColorFg" "ButtonFontSelect"
		"Econ.Button.PresetDefaultColorBg" "ButtonBG"
		"Econ.Button.PresetArmedColorBg" "ButtonBGArmed"
		"Econ.Button.PresetDepressedColorBg" "ButtonBGSelect"
		"Border.Bright" "Blank"
		"Border.Dark" "Black"
		"Border.Selection" "Gray"
		"Button.TextColor" "ButtonFont"
		"Button.BgColor" "ButtonBG"
		"Button.ArmedTextColor" "ButtonFontArmed"
		"Button.ArmedBgColor" "ButtonBGArmed"
		"Button.SelectedTextColor" "ButtonBGSelect"
		"Button.SelectedBgColor" "ButtonBGSelect"
		"Button.DepressedTextColor" "ButtonFontSelect"
		"Button.DepressedBgColor" "ButtonBGSelect"
		"CheckButton.TextColor" "Yellow"
		"CheckButton.SelectedTextColor" "Yellow"
		"CheckButton.BgColor" "TransparentBlack"
		"CheckButton.Border1" "Yellow"
		"CheckButton.Border2" "Yellow"
		"CheckButton.Check" "Yellow"
		"CheckButton.HighlightFgColor" "Yellow"
		"ComboBoxButton.ArrowColor" "TanLight"
		"ComboBoxButton.ArmedArrowColor" "TanLight"
		"ComboBoxButton.BgColor" "Blank"
		"ComboBoxButton.DisabledBgColor" "Blank"
		"Frame.BgColor" "TransparentBlack"
		"Frame.OutOfFocusBgColor" "TransparentBlack"
		"Frame.FocusTransitionEffectTime" "0.0"
		"Frame.TransitionEffectTime" "0.0"
		"Frame.AutoSnapRange" "0"
		"FrameGrip.Color1" "Blank"
		"FrameGrip.Color2" "Blank"
		"FrameTitleButton.FgColor" "Blank"
		"FrameTitleButton.BgColor" "Blank"
		"FrameTitleButton.DisabledFgColor" "Blank"
		"FrameTitleButton.DisabledBgColor" "Blank"
		"FrameSystemButton.FgColor" "Blank"
		"FrameSystemButton.BgColor" "Blank"
		"FrameSystemButton.Icon" ""
		"FrameSystemButton.DisabledIcon" ""
		"FrameTitleBar.TextColor" "Orange"
		"FrameTitleBar.BgColor" "Blank"
		"FrameTitleBar.DisabledTextColor" "Orange"
		"FrameTitleBar.DisabledBgColor" "Blank"
		"GraphPanel.FgColor" "Orange"
		"GraphPanel.BgColor" "TransparentBlack"
		"Label.TextDullColor" "TanDark"
		"Label.TextColor" "TanLight"
		"Label.TextBrightColor" "TanLight"
		"Label.SelectedTextColor" "White"
		"Label.BgColor" "Blank"
		"Label.DisabledFgColor1" "Blank"
		"Label.DisabledFgColor2" "Black"
		"ListPanel.TextColor" "Orange"
		"ListPanel.BgColor" "TransparentBlack"
		"ListPanel.SelectedTextColor" "Black"
		"ListPanel.SelectedBgColor" "Red"
		"ListPanel.SelectedOutOfFocusBgColor" "Red"
		"ListPanel.EmptyListInfoTextColor" "Orange"
		"Menu.TextColor" "TanLight"
		"Menu.BgColor" "TransparentBlack"
		"Menu.ArmedTextColor" "TanDark"
		"Menu.ArmedBgColor" "TanLight"
		"Menu.TextInset" "6"
		"Chat.TypingText" "Orange"
		"Panel.FgColor" "Gray"
		"Panel.BgColor" "Blank"
		"HTML.BgColor" "Blank"
		"ProgressBar.FgColor" "ProgressOffWhite"
		"ProgressBar.BgColor" "ProgressBackground"
		"CircularProgressBar.FgColor" "White"
		"CircularProgressBar.BgColor" "White"
		"BuildingHealthBar.BgColor" "HealthBgGrey"
		"BuildingHealthBar.Health" "ProgressOffWhite"
		"BuildingHealthBar.LowHealth" "LowHealthRed"
		"PropertySheet.TextColor" "Orange"
		"PropertySheet.SelectedTextColor" "Orange"
		"PropertySheet.TransitionEffectTime" "0.25"
		"RadioButton.TextColor" "Orange"
		"RadioButton.SelectedTextColor" "Orange"
		"RichText.TextColor" "Gray"
		"RichText.BgColor" "Blank"
		"RichText.SelectedTextColor" "Gray"
		"RichText.SelectedBgColor" "Red"
		"ScrollBarButton.FgColor" "Gray"
		"ScrollBarButton.BgColor" "Blank"
		"ScrollBarButton.ArmedFgColor" "Gray"
		"ScrollBarButton.ArmedBgColor" "Blank"
		"ScrollBarButton.DepressedFgColor" "Black"
		"ScrollBarButton.DepressedBgColor" "Blank"
		"ScrollBarSlider.FgColor" "Gray"
		"ScrollBarSlider.BgColor" "Blank"
		"SectionedListPanel.HeaderTextColor" "Orange"
		"SectionedListPanel.HeaderBgColor" "Blank"
		"SectionedListPanel.DividerColor" "Black"
		"SectionedListPanel.TextColor" "Orange"
		"SectionedListPanel.BrightTextColor" "Orange"
		"SectionedListPanel.BgColor" "TransparentLightBlack"
		"SectionedListPanel.SelectedTextColor" "Black"
		"SectionedListPanel.SelectedBgColor" "Red"
		"SectionedListPanel.OutOfFocusSelectedTextColor" "Black"
		"SectionedListPanel.OutOfFocusSelectedBgColor" "255 255 255 32"
		"Slider.NobColor" "108 108 108 255"
		"Slider.TextColor" "127 140 127 255"
		"Slider.TrackColor" "31 31 31 255"
		"Slider.DisabledTextColor1" "117 117 117 255"
		"Slider.DisabledTextColor2" "30 30 30 255"
		"TextEntry.TextColor" "Gray"
		"TextEntry.BgColor" "Blank"
		"TextEntry.CursorColor" "Gray"
		"TextEntry.DisabledTextColor" "Gray"
		"TextEntry.DisabledBgColor" "Blank"
		"TextEntry.SelectedTextColor" "TanLight"
		"TextEntry.SelectedBgColor" "Gray"
		"TextEntry.OutOfFocusSelectedBgColor" "Blank"
		"TextEntry.FocusEdgeColor" "Blank"
		"ToggleButton.SelectedTextColor" "Orange"
		"Tooltip.TextColor" "TransparentBlack"
		"Tooltip.BgColor" "Red"
		"TreeView.BgColor" "TransparentBlack"
		"WizardSubPanel.BgColor" "Blank"
		"TimerProgress.Active" "HudTimerProgressActive"
		"TimerProgress.InActive" "HudTimerProgressInActive"
		"TimerProgress.Warning" "HudTimerProgressWarning"
		"HudObjectives.FgColor" "HudPanelForeground"
		"HudObjectives.BgColor" "HudPanelBackground"
		"HudObjectives.BorderColor" "HudPanelBorder"
		"HudProgressBar.Active" "HudProgressBarActive"
		"HudProgressBar.InActive" "HudProgressBarInActive"
		"HudCaptureIcon.Active" "HudProgressBarActive"
		"HudCaptureIcon.InActive" "HudProgressBarInActive"
		"HudCaptureProgressBar.Active" "HudProgressBarActive"
		"HudCaptureProgressBar.InActive" "HudProgressBarInActive"
		"FgColor" "Orange"
		"BgColor" "TransparentBlack"
		"ViewportBG" "Blank"
		"TeamSpec" "204 204 204 255"
		"TeamRed" "RedTeamColor"//"255 64 64 255"
		"TeamBlue" "BlueTeamColor"//"153 204 255 255"
		"MapDescriptionText" "Gray"
		"HudIcon_Green" "0 160 0 255"
		"HudIcon_Red" "160 0 0 255"
		"ItemColor" "255 167 42 200"
		"MenuColor" "233 208 173 255"
		"MenuBoxBg" "0 0 0 100"
		"SelectionNumberFg" "251 235 202 255"
		"SelectionTextFg" "251 235 202 255"
		"SelectionEmptyBoxBg" "0 0 0 80"
		"SelectionBoxBg" "0 0 0 80"
		"SelectionSelectedBoxBg" "0 0 0 190"
		"HintMessageFg" "255 255 255 255"
		"HintMessageBg" "0 0 0 60"
		"ProgressBarFg" "255 30 13 255"
		"Main.Menu.X" "32"
		"Main.Menu.Y" "248"
		"Main.BottomBorder" "32"
		"VguiScreenCursor" "255 208 64 255"

	}
	"BitmapFontFiles" 
	{
	"Buttons" "materials/vgui/fonts/buttons_32.vbf"
	}
	"CustomFontFiles" 
 	{
 		"1" "resource/tf.otf"
 		"2" "resource/tfd.otf"
		"5"
 		{
 		"font" "resource/customfonts/GlacialIndifference-Regular.otf"
 		"name" "GlacialIndifference-Regular"
 		}
		"6"
 		{
 		"font" "resource/customfonts/GlacialIndifference-Bold.otf"
 		"name" "GlacialIndifference-Bold"
 		}
 		"7" 
 		{
 		"font" "resource/customfonts/DIN 1451 Mittelschrift.otf"
 		"name" "DIN 1451 Mittelschrift"
 		}
 		"8"
 		{
 		"font" "resource/customfonts/Lato-Black.ttf"
 		"name" "Lato Black"
 		}
		"9"
 		{
 		"font" "resource/customfonts/Orbitron-Bold.ttf"
 		"name" "Orbitron Bold"
 		}
		"10"
 		{
 		"font" "resource/customfonts/AvenirLTStd-Heavy-edited.otf"
 		"name" "AvenirLTStd-Heavy-edited"
 		}
 		"11" 
 		{
 		"font" "resource/crosshairs.otf"
 		"name" "Crosshairs"
 		}
 		"12"
		{
			"font" "resource/TF2.ttf"
			"name" "TF2"
			"russian"
			{
				"range" "0x0000 0xFFFF"
			}
			"polish"
			{
				"range" "0x0000 0xFFFF"
			}
		}
		"13" 
		{
			"font" "resource/TF2Secondary.ttf"
			"name" "TF2 Secondary"
			"russian"
			{
				"range" "0x0000 0xFFFF"
			}
			"polish"
			{
				"range" "0x0000 0xFFFF"
			}
		}
		"14" 
		{
			"font" "resource/TF2Professor.ttf"
			"name" "TF2 Professor"
			"russian"
			{
				"range" "0x0000 0x00FF"
			}
			"polish"
			{
				"range" "0x0000 0x00FF"
			}
		}	
		"15" 
		{
			"font" "resource/TF2Build.ttf"
			"name" "TF2 Build"
			"russian"
			{
				"range" "0x0000 0xFFFF"
			}
			"polish"
			{
				"range" "0x0000 0xFFFF"
			}
			"turkish"
			{
				"range" "0x0000 0xFFFF"
			}
		}	
		// add your new font files here
		// with a number larger than the preceding
		// and curly brackets enclosing them
		// in this format:
		// "16"
		// {
		// 		"font" "path/to/font"
		//		"name" "PostScriptNameOfFont"
		//		// use your OS's font viewer
		// }
 	}
}
